services:
  db:
    image: mysql:8.0  
    container_name: cuchinetworks_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: CuchiNetworks
      MYSQL_USER: CuchiNetworks
      MYSQL_PASSWORD: ositoBimbo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  backend:
    build: ./backend
    container_name: cuchinetworks_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=CuchiNetworks
      - DB_PASSWORD=ositoBimbo
      - DB_NAME=CuchiNetworks
      - DB_PORT=3306
      - JWT_SECRET=tu_clave_super_secreta_y_larga
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: cuchinetworks_client
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

# DEFINICIÃ“N DEL VOLUMEN
volumes:
  mysql_data: