version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cuchinetworks_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: CuchiNetworks
      MYSQL_USER: CuchiNetworks
      MYSQL_PASSWORD: ositoBimbo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Esto carga tu script SQL autom√°ticamente al iniciar
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: